export { default as AboutSection } from './components/AboutSection.vue'
export { default as ExperienceTimeline } from './components/ExperienceTimeline.vue'
export { default as HeroSection } from './components/HeroSection.vue'
export { default as PortfolioCard } from './components/PortfolioCard.vue'
export { default as ProjectShowcase } from './components/ProjectShowcase.vue'
export type { Experience, Project, Skill } from './types'
export { default as HomeView } from './views/HomeView.vue'
